import raw from "../public/data/cfb-2026.json";
import type { CfbData, TeamBudget } from "./types";

// Generated by `npm run build-data`. Re-run the pipeline after editing data/.
export const data = raw as unknown as CfbData;

export function getTeam(slug: string): TeamBudget | undefined {
  return data.teams.find((t) => t.slug === slug);
}

export function rankedTeams(): TeamBudget[] {
  return data.teams.filter((t) => t.ap_rank != null);
}

export function conferencePeers(team: TeamBudget): TeamBudget[] {
  return data.teams
    .filter((t) => t.conference === team.conference)
    .sort((a, b) => b.budget_mid_m - a.budget_mid_m);
}
